apiVersion: v1
kind: Service
metadata:
  name: deepseek-service
  namespace: deepseek
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: webui
  - port: 11434
    targetPort: 11434
    protocol: TCP
    name: ollama
  selector:
    app: deepseek
